### ISSUE TITLE
How SnapIt works

### ISSUE THREAD

**Issue by Melli2107** [Snapit-HHZ/snapit-hhz#12]
[Funktionsweise SnapIt.pptx](https://github.com/Snapit-HHZ/snapit-hhz/files/1669065/Funktionsweise.SnapIt.pptx)

**Comment by drohhz** [comment]
![how snapit work](https://user-images.githubusercontent.com/33895792/35563136-1286a0bc-05b6-11e8-997f-7feb6ce05a9a.PNG)
