### ISSUE TITLE
Business Modell Canvas_15.01.2018

### ISSUE THREAD

**Issue by PaulaSchmelzer** [Snapit-HHZ/snapit-hhz#6]
[Snapit-HHZ_Business.Model.Canvas.pptx](https://github.com/Snapit-HHZ/snapit-hhz/files/1632552/Snapit-HHZ_Business.Model.Canvas.pptx)

**Comment by melissa2709** [comment]
[Snapit-HHZ_Business.Model.Canvas.pdf](https://github.com/Snapit-HHZ/snapit-hhz/files/1664179/Snapit-HHZ_Business.Model.Canvas.pdf)

**Comment by melissa2709** [comment]
![slide1](https://user-images.githubusercontent.com/12093969/35391222-54a87cf8-01de-11e8-94e7-234267ebff58.jpg)
